[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
game_won = true
G.GAME.won = true
'''
position = "before"
payload = '''if not (G.GAME and G.GAME.selected_back and G.GAME.selected_back.effect and G.GAME.selected_back.effect.center.key == "b_gstpst_distracted") then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
game_won = true
G.GAME.won = true
'''
position = "after"
payload = '''end'''
match_indent = true